[package]
name = "rcat"
description = "Rust version of cat utility, concatenate files and print on the standard output"
version = "2.1.0"
authors = ["Pierre Violent"]
edition = "2024"

[package.metadata]
copyright = "Copyright Â©2025-2026 Pierre Violent"

[dependencies]
myglob = { path = "../../Crates/MyGlob" }
mymarkup = { path = "../../Crates/MyMarkup" }
getopts = "0.2.24"

[build-dependencies]
toml = "1.0.1"
winres = "0.1.12"
cargo_metadata = "0.23.1"
