[package]
name = "runiq"
description = "Rust version of uniq, report or omit repeated lines"
version = "1.0.0"
authors = ["Pierre Violent"]
edition = "2024"

[dependencies]
mymarkup = { path = "../../Crates/MyMarkup" }
getopt = "1.1.7"
indexmap = "2.12.0"

[build-dependencies]
toml = "1.0.1"
